/** Stage a creator-exported package. Publishing is a separate command after review. */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { readPackageFile, writePackageArchive, verifyPackageIntegrity } from '../../src/project/packageArchive';
import { isRetiredStoreSlug } from '../../src/marketplace/retiredPackages';

const args = process.argv.slice(2);
const option = (name: string) => { const at = args.indexOf(name); return at < 0 ? undefined : args[at + 1]; };
const source = args[0], slug = option('--slug'), license = option('--license');
if (!source || source.startsWith('--') || !slug || !/^[a-z0-9-]+$/.test(slug) || !license) {
  throw new Error('Usage: npm run store:add -- /path/package.nfpack --slug my-package --license MIT [--version 1.0.0]');
}
if (isRetiredStoreSlug(slug)) throw new Error('This slug is retired; choose a new package identity.');
if (['ui-kit-party-royale', 'ui-kit-rpg-hud', 'arbor-forge', 'model-forge'].includes(slug)) throw new Error('This package is generated by the catalog builder. Edit its authored definition instead.');
const archive = readPackageFile(new Uint8Array(await readFile(resolve(source))));
await verifyPackageIntegrity(archive);
for (const asset of archive.pkg.assets) {
  if (!archive.bytes.has(asset.id)) throw new Error(`Embed asset bytes before publishing: ${asset.name}.`);
}
const catalog = JSON.parse(await readFile('public/store/catalog.json', 'utf8'));
const existing = catalog.packages.find(entry => entry.slug === slug);
const version = option('--version') ?? archive.pkg.meta.version;
if (!/^\d+\.\d+\.\d+(?:[-+][a-zA-Z0-9.-]+)?$/.test(version)) throw new Error('Choose a semantic package version, such as 1.0.0.');
archive.pkg.meta = { ...archive.pkg.meta, id: existing?.id ?? `pkg-feather-${slug}`, license, version };
const folder = { asset: 'assets', project: 'projects', plugin: 'plugins' }[archive.pkg.kind];
if (!folder) throw new Error('Only asset, project and plugin packages can be staged.');
const target = resolve('.feather-cache/store/packages', folder, `${slug}.nfpack`);
await mkdir(dirname(target), { recursive: true });
await writeFile(target, writePackageArchive(archive.pkg, archive.bytes, { mtime: new Date('2026-01-01T00:00:00Z') }));
console.log(`Staged ${slug} v${version} (${archive.pkg.kind}, ${license}). Run build:store, capture/review, then store:publish.`);
