import type { SceneObjectKind, Vector3Tuple } from '../types/common';

export type SimpleInteractionTriggerType =
  | 'interact'
  | 'collision'
  | 'trigger-enter'
  | 'trigger-exit'
  | 'start'
  | 'timer'
  | 'health-zero';

export type SimpleInteractionActionType =
  | 'move'
  | 'rotate'
  | 'scale'
  | 'destroy'
  | 'damage'
  | 'score'
  | 'play-animation'
  | 'play-sound'
  | 'spawn'
  | 'event';

export interface SimpleInteractionTrigger {
  type: SimpleInteractionTriggerType;
  /** Repeating interval for timer triggers. */
  seconds?: number;
}

export interface SimpleInteractionAction {
  type: SimpleInteractionActionType;
  /** Target position/rotation/scale for transform actions. */
  vector?: Vector3Tuple;
  /** Damage or score amount. */
  value?: number;
  assetId?: string;
  animationId?: string;
  eventName?: string;
  spawnKind?: SceneObjectKind;
}

/**
 * Beginner-authored rule. This metadata is only an editor representation: execution always comes
 * from the normal Blueprint graph generated by {@link compileSimpleInteractionBlock}.
 */
export interface SimpleInteraction {
  id: string;
  trigger: SimpleInteractionTrigger;
  action: SimpleInteractionAction;
  duration?: number;
  then?: SimpleInteractionAction[];
  params?: Record<string, unknown>;
}

export type SimpleInteractionDraft = Omit<SimpleInteraction, 'id'>;

export const SIMPLE_TRIGGER_LABELS: Record<SimpleInteractionTriggerType, string> = {
  interact: 'Player interacts',
  collision: 'Object collides',
  'trigger-enter': 'Object enters',
  'trigger-exit': 'Object exits',
  start: 'Game starts',
  timer: 'Timer fires',
  'health-zero': 'Health reaches 0',
};

export const SIMPLE_ACTION_LABELS: Record<SimpleInteractionActionType, string> = {
  move: 'Move object',
  rotate: 'Rotate object',
  scale: 'Scale object',
  destroy: 'Destroy this object',
  damage: 'Deal damage',
  score: 'Add score',
  'play-animation': 'Play animation',
  'play-sound': 'Play sound',
  spawn: 'Spawn object',
  event: 'Fire event',
};

const finite = (value: number | undefined, fallback: number, minimum?: number) => {
  const next = Number.isFinite(value) ? Number(value) : fallback;
  return minimum === undefined ? next : Math.max(minimum, next);
};

const vector = (value: Vector3Tuple | undefined, fallback: Vector3Tuple): string => {
  const next = value ?? fallback;
  return `vec3(${next.map((item) => finite(item, 0)).join(', ')})`;
};

const quote = (value: string | undefined, fallback: string): string => JSON.stringify(value?.trim() || fallback);

const eventTarget = (trigger: SimpleInteractionTriggerType): string => {
  if (trigger === 'interact') return 'player';
  if (trigger === 'collision' || trigger === 'trigger-enter' || trigger === 'trigger-exit') return 'other';
  return 'self';
};

const actionLine = (action: SimpleInteractionAction, interaction: SimpleInteraction): string => {
  const duration = finite(interaction.duration, 0.8, 0.01);
  switch (action.type) {
    case 'move':
      return `tween(self, property: "position", to: ${vector(action.vector, [0, 1, 0])}, duration: ${duration})`;
    case 'rotate':
      return `tween(self, property: "rotation", to: ${vector(action.vector, [0, 90, 0])}, duration: ${duration})`;
    case 'scale':
      return `tween(self, property: "scale", to: ${vector(action.vector, [1.25, 1.25, 1.25])}, duration: ${duration})`;
    case 'destroy':
      return 'destroy(self)';
    case 'damage':
      return `apply_damage(${eventTarget(interaction.trigger.type)}, ${finite(action.value, 10, 0)})`;
    case 'score':
      return `Game.Score = (Game.Score + ${finite(action.value, 10)})`;
    case 'play-animation':
      return `play_animation(${quote(action.animationId, 'animation')})`;
    case 'play-sound':
      return `Audio.play(${quote(action.assetId, 'sound')})`;
    case 'spawn':
      return `spawn_object(${quote(action.spawnKind, 'cube')})`;
    case 'event':
      return `fire_event(${quote(action.eventName, 'CreatorEvent')})`;
  }
};

const triggerLine = (trigger: SimpleInteractionTrigger): string => {
  switch (trigger.type) {
    case 'interact': return 'on interact(player):';
    case 'collision': return 'on collision_enter(other):';
    case 'trigger-enter': return 'on trigger_enter(other):';
    case 'trigger-exit': return 'on trigger_exit(other):';
    case 'start': return 'on start:';
    case 'timer': return `on timer(${finite(trigger.seconds, 1, 0.05)}):`;
    case 'health-zero': return 'on receive_damage(amount):';
  }
};

/** Compile one rule into valid FeatherScript handlers (without a blueprint declaration). */
export const compileSimpleInteractionBlock = (interaction: SimpleInteraction): string => {
  const body: string[] = [];
  if (interaction.trigger.type === 'health-zero') {
    body.push('self.health = (self.health - amount)', 'if (self.health <= 0):');
    body.push(`    ${actionLine(interaction.action, interaction)}`);
    for (const action of interaction.then ?? []) body.push(`    ${actionLine(action, interaction)}`);
  } else {
    body.push(actionLine(interaction.action, interaction));
    for (const action of interaction.then ?? []) body.push(actionLine(action, interaction));
  }
  return [triggerLine(interaction.trigger), ...body.map((line) => `    ${line}`)].join('\n');
};

const safeBlueprintName = (name: string): string => {
  const safe = name.trim().replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  return safe || 'Creator_Logic';
};

/** Add a generated handler without disturbing existing graph-authored behavior or detached timelines. */
export const appendSimpleInteractionToFeatherSource = (
  source: string | undefined,
  interaction: SimpleInteraction,
  blueprintName: string,
): string => {
  const declaration = `blueprint ${safeBlueprintName(blueprintName)}`;
  const normalized = source?.trim()
    ? source.trim().replace(/^\s*blueprint\s+\S+.*$/m, declaration)
    : declaration;
  const block = compileSimpleInteractionBlock(interaction);
  const detachedAt = normalized.search(/^detached:\s*$/m);
  if (detachedAt < 0) return `${normalized}\n\n${block}`;
  const before = normalized.slice(0, detachedAt).trimEnd();
  const detached = normalized.slice(detachedAt).trimStart();
  return `${before}\n\n${block}\n\n${detached}`;
};

export const simpleInteractionUsesScore = (interaction: SimpleInteraction): boolean =>
  interaction.action.type === 'score' || Boolean(interaction.then?.some((action) => action.type === 'score'));
